# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'stickynotes' do

pod 'stickynote', :path => 'stickyapi'
pod 'Starscream', '~> 4.0.0'

target 'gRPCTests' do
   inherit! :search_paths
   # Pods for testing
 end

target 'RESTTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'SocketTests' do
  inherit! :search_paths
  # Pods for testing
end

end

