#!/bin/sh

echo "1. Initiating tests"

#check if xcpretty is installed.

action="test"; target=""; 

for last; do true; done
count=${last:-1}

regex='^[0-9]+$' #check if last argument is a number, if not set it to 1.
if ! [[ $count =~ $regex ]] ; then
   count=1
fi

echo "count $count"

while (( "$#" )); do
   case "$1" in
      --rest)  
			target="RESTTests/RESTTests"
            ;;
      --grpc)     
			target="gRPCTests/gRPCTests"
            ;;
      --socket) 
			echo "ERROR: Not yet setup"
            ;;
      --without-building) 
            action="test-without-building" 
            ;;               
      *) 
   esac        
   shift
done

echo "Initiating: $action with target $target"

perform_tests() {
	if [ "$target" = "" ]; then
  		xcodebuild "$action" \
  		-scheme stickynotes \
  		-workspace stickynotes.xcworkspace \
  		-destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -r junit --report html # OS=13.3' TODO: add the device's OS picking logic.
  	else
  		xcodebuild "$action" \
  		-scheme stickynotes \
  		-workspace stickynotes.xcworkspace \
  		-destination 'platform=iOS Simulator,name=iPhone 8' \
  		-only-testing "$target" | xcpretty -r junit --report html
	fi
}

for ((i=0; i<count; i++)); do perform_tests; done #execute the tests 'count' nuber of times. used C style loop as 'for i in {1..$count}' does not work!
